### ISSUE TITLE
Run build

### ISSUE THREAD

**Issue by lamka-tatya** [shurupov/otus-react-js-learning#18]
При запуске команды "npm run build" генерится нерабочая html-ка.
При её открытии в консоли возникает ошибка 
`Uncaught DOMException: Failed to execute 'replaceState' on 'History`

**Comment by shurupov** [comment]
У меня всё открывается. Exception (другой, но связанный с DOM и History) возникает, когда жмёшь ссылку, у которой href абсолютный. Т.е. ссылка в этом случае ссылается на некую несуществующую папку в корне файловой системы (для Windows это будет корень диска C:, например). Впрочем, возможно, в Windows Exception другой, но уверен, связано это с тем же.
Если же запустить приложение не через html-файл из файловой системы, а через запуск сервера, например через команду `npx node-static .` в папке dist, то всё работает, и ссылки тоже.
Поскольку приложение не предназначалось для запуска из файловой системы, то в данном случае это не баг.
@lamka-tatya проверь как работает приложение через запуск сервера командой `npx node-static .` в папке dist, с этой html-кой. Если всё ок, то предлагаю закрыть этот баг.

**Comment by lamka-tatya** [comment]
Через `npx node-static` все работает. Закрываю.
