### ISSUE TITLE
Reload leads to loss of auth

### ISSUE THREAD

**Issue by lamka-tatya** [shurupov/otus-react-js-learning#19]
Как воспроизвести:

1. Залогиться под каким-то именем
2. Начать играть в игру
3. Нажать F5

Ошибка: перекидывает на окно логина, сбрасывает текущую аутентификацию.
Ожидаемое поведение: при перезагрузке страницы текущий пользователь не сбрасывается, выход осуществляется только через кнопку Logout.

**Comment by shurupov** [comment]
Починено в ветке issue-16-auth-bug (При создании ветки допустил опечатку вместо issue-19 ввёл issue-16)

**Comment by shurupov** [comment]
Сделал PR этой ветки #22
